server:
  port: 80

fruit:
  list:
    - name: banana
      color: yellow
    - name: apple
      color: red
    - name: water melon
      color: green
datasource:
  url: jdbc:h2:mem:testdb

spring:
  h2:
    console:
      enabled: true
  thymeleaf:
    cache: false

property:
  test:
    name: property depth test
propertyTest: test
PropertyTestList: a,b,c
---

spring:
  config:
    activate:
      on-profile: local

server:
  port: 8081
---

spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8082
